export const COMPANY_VALIDATE_SUCCESS = "COMPANY_VALIDATE_SUCCESS";
export const COMPANY_VALIDATE_ERROR = "COMPANY_VALIDATE_ERROR";
export const FEED_VALIDATE_SUCCESS = "FEED_VALIDATE_SUCCESS";
export const FEED_VALIDATE_ERROR = "FEED_VALIDATE_ERROR";
export const SOCKET_CONNECTION_SUCCESS = "SOCKET_CONNECTION_SUCCESS";
export const SOCKET_CONNECTION_ERROR = "SOCKET_CONNECTION_ERROR";
export const SOCKET_FEED_RESPONSE_SUCCESS = "SOCKET_FEED_RESPONSE_SUCCESS";
